biblioweb/account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('registration/', views.registration, name='registration'),
    path('logout/', views.logout_user, name='logout'),
]

biblioweb/books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path('authors/', views.authors, name='authors'),
    path('read/<slug:slug>/', views.read, name='read'),
    path('genre/<int:genre_id>/', views.genre, name='genre'),
    path('<slug:slug>/', views.detail, name='detail'),
    path('', views.index, name='index'),
]

biblioweb/main/urls.py
from django.urls import path, include
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('biblioweb.account.urls')),
    path('books/', include('biblioweb.books.urls')),
    path('', include('biblioweb.main.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

biblioweb/account/models.py
from django.db import models

# Create your models here.

biblioweb/books/models.py
from django.db import models


class Author(models.Model):

    GENDER_MALE = "M"
    GENDER_FEMALE = "F"

    GENDER_CHOICES = [
        (None, "Género"),
        (GENDER_MALE, "Masculino"),
        (GENDER_FEMALE, "Femenino"),
    ]

    name = models.CharField(verbose_name='Name', max_length=75)
    surname = models.CharField(verbose_name='Surname', max_length=75)
    gender = models.CharField(
        verbose_name='Gender', max_length=9,  blank=False, choices=GENDER_CHOICES)
    avatar = models.CharField(verbose_name='Avatar URL', max_length=255)

    def __str__(self) -> str:
        return f'{self.name} {self.surname}'


class Genre(models.Model):
    name = models.CharField(verbose_name='Name', max_length=255)
    description = models.TextField(
        verbose_name='Description', db_default='No description')

    def __str__(self) -> str:
        return self.name


class Cover(models.Model):
    alt = models.CharField(verbose_name='Alternative text', max_length=255)
    image = models.ImageField(verbose_name='Image',
                              upload_to='images/covers/', null=True, blank=True)


class Book(models.Model):
    isbn = models.CharField(verbose_name='ISBN', max_length=13)
    title = models.CharField(verbose_name='Title', max_length=125)
    slug = models.CharField(verbose_name='Slug', max_length=125)
    language = models.CharField(verbose_name='Language', max_length=125)
    org_language = models.CharField(
        verbose_name='Original language', max_length=125)
    pub_year = models.IntegerField(verbose_name='Year of publication')
    pages = models.IntegerField(verbose_name='No. of pages')
    rating = models.IntegerField(verbose_name='Rating', db_default=0)
    description = models.TextField(
        verbose_name='Description', db_default='No description')
    blurb = models.TextField(verbose_name='Blurb', db_default='No blurb')
    authors = models.ManyToManyField(Author)
    genres = models.ManyToManyField(Genre)
    cover = models.OneToOneField(
        Cover, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.title


class Award(models.Model):
    book = models.ForeignKey(
        Book, on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(verbose_name='Name', max_length=125)

    def __str__(self) -> str:
        return self.name

biblioweb/account/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class RegistrationForm(forms.Form):
    email = forms.EmailField()
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

biblioweb/account/views.py
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.urls import reverse
from .forms import LoginForm, RegistrationForm


def login_user(request: HttpRequest) -> HttpResponse:

    if request.method == 'POST':
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            cd = login_form.cleaned_data
            user = authenticate(
                username=cd['username'], password=cd['password'])
            if user is not None:
                login(request, user)
                print('User succesuffly logged in!')
                return HttpResponseRedirect(reverse('main:index'))
            else:
                print('Username or password is incorrect.')
                return HttpResponse('Username or password is incorrect.')
        else:
            login_form = LoginForm(request.POST)
            return render(request, 'account/login.html', {'form': login_form})

    if request.method == 'GET':
        login_form = LoginForm()
        return render(request, 'account/login.html', {'form': login_form})


def registration(request: HttpRequest) -> HttpResponse:
    if request.method == 'POST':
        registration_form = RegistrationForm(request.POST)
        if registration_form.is_valid():
            cd = registration_form.cleaned_data
            user = User.objects.create_user(
                username=cd['username'], email=cd['email'], password=cd['password'])
            return HttpResponseRedirect(reverse('account:login'))
        else:
            registration_form = RegistrationForm(request.POST)
            return render(request, 'account/registration.html', {'form': registration_form})

    if request.method == 'GET':
        registration_form = RegistrationForm()
        return render(request, 'account/registration.html', {'form': registration_form})


def logout_user(request: HttpRequest) -> HttpResponse:
    logout(request)
    return HttpResponseRedirect(reverse('main:index'))

biblioweb/books/views.py
from django.conf import settings
from django.http import HttpResponse, HttpRequest, Http404
from django.shortcuts import render
from .models import Book, Genre, Author
from .utils import get_line_indices_for_paragraphs, get_list_of_total_pages
from pathlib import Path
import markdown


def index(request: HttpRequest) -> HttpResponse:
    books = Book.objects.all()
    genres = Genre.objects.all()
    context = {
        "books": books,
        "genres": genres
    }
    return render(request, 'books.html', context)


def detail(request: HttpRequest, slug: str) -> HttpResponse:
    try:
        book = Book.objects.get(slug=slug)
    except Book.DoesNotExist:
        raise Http404("This book does not exist.")
    return render(request, 'book-detail.html', {"book": book})


def genre(request: HttpRequest, genre_id: int) -> HttpResponse:
    genres = Genre.objects.all()
    books = Book.objects.filter(genres__id=genre_id)

    try:
        selected_genre = Genre.objects.get(pk=genre_id)
    except Genre.DoesNotExist:
        raise Http404("This genre does not exist.")

    context = {
        "books": books,
        "genres": genres,
        "selected_genre": selected_genre,
    }
    return render(request, 'book-genre.html', context)


def authors(request: HttpRequest) -> HttpResponse:
    authors = Author.objects.all()
    context = {"authors": authors}
    return render(request, 'authors.html', context)


def read(request: HttpRequest, slug: str) -> HttpResponse:
    page = int(request.GET.get('page', 1))
    chapter = int(request.GET.get('chapter', 1))

    try:
        book = Book.objects.get(slug=slug)
    except Book.DoesNotExist:
        raise Http404("This book does not exist.")

    try:
        chapter_path = Path(
            settings.BASE_DIR /
            f'biblioweb/books/static/books/{book.slug}/ch{chapter}.txt'
        )

        chapters_dir = Path(
            settings.BASE_DIR /
            f'biblioweb/books/static/books/{book.slug}'
        )

        chapters = []
        chapter_count = 0

        for root, dirs, files in chapters_dir.walk(on_error=print):

            for file in files:
                chapter_count += 1
                print(f'chapter_count: {chapter_count}')
            chapters = range(1, chapter_count + 1)

        with chapter_path.open() as chapter_file:
            chapter_content = ''

            raw_lines = chapter_file.readlines()
            lines = [line for line in raw_lines if line != '\n']

            paragraphs_per_page = 9  # TODO: Make this value dynamic or configurable
            list_of_page_numbers = get_list_of_total_pages(
                lines, paragraphs_per_page)

            paragraphs_indices = get_line_indices_for_paragraphs(
                page, lines, paragraphs_per_page)

            for i in paragraphs_indices:
                chapter_content += markdown.markdown(lines[i])

    except FileNotFoundError as err:
        print(f'File \'{err.filename}\' does not exists):')

    context = {
        "book": book,
        "chapter": chapter,
        "chapter_content": chapter_content,
        "page": page,
        "list_of_page_numbers": list_of_page_numbers,
        "list_of_chapter_numbers": chapters,
    }
    return render(request, 'book-read.html', context)

biblioweb/main/views.py
from django.http import HttpResponse, HttpRequest
from django.shortcuts import render
from biblioweb.books.models import Book


def index(request: HttpRequest) -> HttpResponse:
    books = Book.objects.all()
    return render(request, 'index.html', {"books": books})

biblioweb/templates/authors.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Biblioweb | Autores{% endblock title %}

{% block content %}
  <nav aria-label="breadcrumbs" class="container section breadcrumbs">
    <ol class="breadcrumb-list" role="list">
      <li class="breadcrumb-item">
        <a class="breadcrumb-link" href="{% url 'books:index' %}">Libros</a>
      </li>
      <li class="breadcrumb-item">
        <a
          class="breadcrumb-link"
          href="{% url 'books:authors' %}"
          aria-current="location"
        >Autores</a>
      </li>
    </ol>
  </nav>
  <section class="container section authors-section">
    <h1 class="h2">Nuestros autores</h1>
    <div class="authors-gallery">
      {% for author in authors %}
        <figure class="author">
          <img class="author-image" src="{{ author.avatar }}" alt="" />
          <figcaption class="author-name">
            {{ author.name }} {{ author.surname }}
          </figcaption>
        </figure>
      {% endfor %}
    </div>
  </section>
  <section class="container section info-section">
    <div class="info-header">
      <h2 class="info-header__title">Lee cómodamente donde quieras</h2>
      <img
        src="{% static 'img/logo-info-section.jpg' %}"
        alt="Logo de Biblioweb: Libro abierto por la mitad con partículas desvaneciéndose del lado derecho"
      />
    </div>
    <div class="info-blocks">
      <div class="info-block">
        <h3>Novelas, clásicos y best-sellers</h3>
        <p>
          Biblioweb es la mayor biblioteca de libros electrónicos de Perú por
          suscripción. Más de 10000 obras en la web: novela policíaca, ciencia
          ficción, fantasía, novela romántica, libros de psicología empresarial,
          para niños, literatura moderna y clásica.
        </p>
      </div>
      <div class="info-block">
        <h3>Cualquier libro por una suscripción</h3>
        <p>
          Todas las obras están incluidas en las suscripciones: estándar o
          premium. Suscríbase a la suscripción Premium para tener acceso completo
          a la biblioteca en línea, o a la suscripción Estándar para leer sólo los
          best-sellers y los clásicos. Puede elegir el periodo de suscripción que
          más le convenga: un mes, tres meses o un año. Se acabó comprar de uno en
          uno.
        </p>
      </div>
      <div class="info-block">
        <h3>Recomendamos los mejores libros</h3>
        <p>
          Nuestras colecciones son una ayuda para elegir las obras adecuadas según
          el estado de ánimo, el tema, la estación del año, la popularidad o el
          criterio de los expertos. Seleccionamos los mejores libros y audiolibros
          en nuestra biblioteca digital para que no tenga que perder tiempo
          buscando. También le informamos sobre los ganadores de premios y
          concursos de libros.
        </p>
      </div>
      <div class="info-block">
        <h3>Estadísticas personales</h3>
        <p>
          Las estadísticas de lectura te motivan a leer más a lo largo de la
          semana, el mes y el año. Cada día registramos el número de páginas
          leídas, dibujamos gráficos en el perfil de la aplicación y enviamos
          estadísticas mensuales a tu correo electrónico. ¿Hace tiempo que no
          retomas el libro? ¡No es el momento de ponerse al día!
        </p>
      </div>
    </div>
  </section>
{% endblock content %}

biblioweb/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Biblioweb{% endblock title %}</title>
    {% block stylesheets %}
      <link rel="stylesheet" href="{% static 'styles.css' %}" />
    {% endblock stylesheets %}
  </head>
  <body>
    <header class="container">
      <div class="header-top">
        <a href="{% url 'main:index' %}">
          <img
            src="{% static 'img/logo-desktop.png' %}"
            alt="Logo de Biblioweb: Libro abierto por la mitad con partículas desvaneciéndose del lado derecho"
          />
        </a>
        <div class="header-searchbar-wrapper">
          <form action="" method="">
            <input
              class="header-searchbar"
              type="search"
              name="search"
              placeholder="Libro o autor"
              aria-placeholder="Buscar por libro o autor"
            />
            <input type="submit" style="display: none" />
          </form>
        </div>
        <button class="header-session-btn">Log in</button><span class="header-session-btn--deco"> // </span><button class="header-session-btn">Sign up</button>
      </div>
      <nav class="page-nav">
        <ul class="page-nav-links" role="list">
          <li class="page-nav-item">
            <a class="page-nav-link" href="{% url 'books:index' %}">Books</a>
          </li>
          <li class="page-nav-item">
            <a class="page-nav-link" href="{% url 'books:authors' %}"
            >Authors</a>
          </li>
          <li class="page-nav-item">
            <a class="page-nav-link" href="#">Ratings</a>
          </li>
          <li class="page-nav-item">
            <a class="page-nav-link" href="#">Subscription</a>
          </li>
          <li class="page-nav-item">
            <a class="page-nav-link" href="{% url 'account:login' %}"
            >Iniciar sesión ➡️</a>
          </li>
          {% if user.is_authenticated %}
            <li class="page-nav-item">
              <a class="page-nav-link" href="{% url 'account:logout' %}"
              >Cerrar sesión ➡️</a>
            </li>
          {% endif %}
        </ul>
      </nav>
    </header>
    <main>
      {% block content %}
        <p>
          Default content (If you see this, maybe you have to override the &#123;%
          block content %&#125; block)
        </p>
      {% endblock content %}
    </main>
    <footer>
      <div class="container">
        <div class="footer-link">
          <h4 class="footer-link__title">Acerca de Biblioweb</h4>
          <ul class="footer-link__link-list" role="list">
            <li>
              <a href="#">Acerca del proyecto</a>
            </li>
            <li>
              <a href="#">Información legal</a>
            </li>
            <li>
              <a href="#">Nosotros</a>
            </li>
            <li>
              <a href="#">Coopera con Biblioweb</a>
            </li>
          </ul>
        </div>
        <div class="footer-link">
          <h4 class="footer-link__title">Acerca del registro</h4>
          <ul class="footer-link__link-list" role="list">
            <li>
              <a href="register.html">Regístrate</a>
            </li>
            <li>
              <a href="#">Cómo registrarse</a>
            </li>
            <li>
              <a href="#">Ayuda</a>
            </li>
          </ul>
        </div>
        <div class="footer-link">
          <h4 class="footer-link__title">Acerca del registro</h4>
          <a class="btn btn-primary footer-link__contact-btn" href="#"
          >8 (025) 752-33-03</a>
        </div>
        <div class="footer-link">
          <h4 class="footer-link__title">Síguenos</h4>
          <ul class="footer-link__link-list footer-link__link-list--social-media" role="list">
            <li class="footer-social-icon-wrapper">
              <a href="#">
                <img
                  src="{% static 'img/icons/instagram-icon.svg' %}"
                  alt="Ícono de Instagram"
                />
              </a>
            </li>
            <li class="footer-social-icon-wrapper">
              <a href="#">
                <img
                  src="{% static 'img/icons/facebook-icon.svg' %}"
                  alt="Ícono de Facebook"
                />
              </a>
            </li>
            <li class="footer-social-icon-wrapper">
              <a href="#">
                <img
                  src="{% static 'img/icons/youtube-icon.svg' %}"
                  alt="Ícono de YouTube"
                />
              </a>
            </li>
            <li class="footer-social-icon-wrapper">
              <a href="#">
                <img
                  src="{% static 'img/icons/twitter-icon.svg' %}"
                  alt="Ícono de Twitter"
                />
              </a>
            </li>
          </ul>
        </div>
      </div>
    </footer>
  </body>
</html>

biblioweb/templates/book-detail.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Book Detail | {{ book.title }}</title>
  </head>
  <body>
    <nav>
      <ul>
        <li>
          <a href="{% url 'main:index' %}">Home</a>
        </li>
        <li>
          <a href="{% url 'books:index' %}">Books</a>
        </li>
        <li>
          <a href="{% url 'books:detail' book.slug %}">{{ book.title }}</a>
        </li>
      </ul>
    </nav>
    <h1>{{ book.title }}</h1>
    {% for author in book.authors.all %}
    <div><b>Autor: </b><span>{{ author }}</span></div>
    {% endfor %}

    <div><b>Año: </b><span>{{ book.pub_year }}</span></div>

    {% for genre in book.genres.all %}
    <div><b>Género: </b><span>{{ genre }}</span></div>
    {% endfor %}

    <div><b> Páginas</b>: <span>{{ book.pages }}</span></div>
    <div><b> Idioma</b>: <span>{{ book.language }}</span></div>
    <div><b> Idioma original</b>: <span>{{ book.org_language }}</span></div>

    {% if book.cover.image %}
    <img src="{{ book.cover.image.url }}" alt="{{ book.cover.alt }}" />
    {% else %}
    <img
      src="{% static 'books/placeholder-cover.jpg' %}"
      alt="Imagen de portada no disponible"
    />
    {% endif %}

    <h2>Description</h2>
    <p>{{ book.description }}</p>

    <h2>Blurb</h2>
    <p>{{ book.blurb }}</p>

    <h2>Awards</h2>
    {% for award in book.award_set.all %}
    <ul>
      <li>{{ award }}</li>
    </ul>
    {% endfor %}

    <a href="{% url 'books:read' book.slug %}">Read this book</a>
  </body>
</html>

biblioweb/templates/book-genre.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Genre | {{ selected_genre.name }}</title>
  </head>
  <body>
    <a href="{% url 'books:index' %}">Return to books page</a>
    <a href="{% url 'main:index' %}">Return to index page</a>
    <h2>Genres</h2>
    <ul>
      {% for genre in genres %}
      <li>
        <a
          href="{% url 'books:genre' genre.id %}"
          {% if genre.id == selected_genre.id %} aria-current="page" style="color: red;" {% endif  %}
          >{{ genre.name }}</a
        >
      </li>
      {% endfor %}
    </ul>
    <h1>Books on {{ selected_genre.name }} genre</h1>
    <p>*Grid of books on this genre*</p>
    {% if books %}
    <ul>
      {% for book in books %}
      <li>
        <a href="{% url 'books:detail' book.slug %}">{{ book.title }}</a>
      </li>
      {% endfor %}
    </ul>
    {% else %}
    <p>There are no books available.</p>
    {% endif %}
  </body>
</html>

biblioweb/templates/book-read.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Read Book | {{ book.title }}</title>
  </head>
  <body>
    <nav>
      <ul>
        <li>
          <a href="{% url 'main:index' %}">Home</a>
        </li>
        <li>
          <a href="{% url 'books:index' %}">Books</a>
        </li>
        <li>
          <a href="{% url 'books:detail' book.slug %}">{{ book.title }}</a>
        </li>
        <li>
          <a href="{% url 'books:read' book.slug %}" aria-current="page"
            >{{ book.title }} (Reading)</a
          >
        </li>
      </ul>
    </nav>

    <h1>Read Book {{ book.title }}</h1>
    <p>{{ book.blurb }}</p>
    <div class="reader" style="border: 2px solid black">
      <form action="{% url 'books:read' book.slug %}" method="GET">
        <select name="chapter" aria-label="Chapter">
          {% for number in list_of_chapter_numbers %}
          <option value="{{ number }}" {% if number  == chapter %}selected{% endif %}>Chapter {{ number }}</option>
          {% endfor %}
        </select>
        <button type="submit">Go</button>
      </form>
      <h1>{{ book.title }}</h1>
      <hr />
      {{ chapter_content | safe }}
      <div>
        {% for number in list_of_page_numbers %}
        <a
          style="
            padding: 0.25rem;
            border: 1px solid black;
            display: inline-block;
          "
          href="{% url 'books:read' book.slug %}?page={{number}}&chapter={{chapter}}"
          >{{ number }},</a
        >
        {% endfor %}
      </div>
    </div>
  </body>
</html>

biblioweb/templates/books.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Biblioweb | Libros{% endblock title %}

{% block content %}
  <nav aria-label="breadcrumbs" class="container section breadcrumbs">
    <ol class="breadcrumb-list" role="list">
      <li class="breadcrumb-item">
        <a
          class="breadcrumb-link"
          href="{% url 'books:index' %}"
          aria-current="location"
        >Libros</a>
      </li>
    </ol>
  </nav>
  <section class="container section gender-section">
    <h1>Géneros</h1>
    <ul class="genres" role="list">
      {% for genre in genres %}
        <li class="genre-item">
          <button class="genre-btn" data-genre-id="genre-id">
            <div class="genre-info">
              <h3 class="genre-title">{{ genre.name }}</h3>
              <p class="genre-book-count">XX</p>
            </div>
            <img
              src="{% static 'img/icons/wizard-hat-icon.svg' %}"
              aria-hidden="true"
            />
          </button>
          <a href="{% url 'books:genre' genre.id %}">{{ genre.name }}</a>
        </li>
      {% endfor %}
    </ul>
  </section>
  <!-- For demo only -->
  <section class="container section books-section">
    <div class="section-information">
      <div class="section-information__header">
        <h2 class="genre-section-title">Género</h2>
        <p id="genre-section-type">
          Los mejores libros de GÉNERO que puedes encontrar.
        </p>
      </div>
      <a href="#" class="section-information__more-link">Más</a>
    </div>
    <!-- This list is initially empty -->
    <ul class="book-list media-scroller" id="book-list" role="list"></ul>
  </section>
  <section class="container section info-section">
    <div class="info-header">
      <h2 class="info-header__title">Lee cómodamente donde quieras</h2>
      <img
        src="{% static 'img/logo-info-section.jpg' %}"
        alt="Logo de Biblioweb: Libro abierto por la mitad con partículas desvaneciéndose del lado derecho"
      />
    </div>
    <div class="info-blocks">
      <div class="info-block">
        <h3>Novelas, clásicos y best-sellers</h3>
        <p>
          Biblioweb es la mayor biblioteca de libros electrónicos de Perú por
          suscripción. Más de 10000 obras en la web: novela policíaca, ciencia
          ficción, fantasía, novela romántica, libros de psicología empresarial,
          para niños, literatura moderna y clásica.
        </p>
      </div>
      <div class="info-block">
        <h3>Cualquier libro por una suscripción</h3>
        <p>
          Todas las obras están incluidas en las suscripciones: estándar o
          premium. Suscríbase a la suscripción Premium para tener acceso completo
          a la biblioteca en línea, o a la suscripción Estándar para leer sólo los
          best-sellers y los clásicos. Puede elegir el periodo de suscripción que
          más le convenga: un mes, tres meses o un año. Se acabó comprar de uno en
          uno.
        </p>
      </div>
      <div class="info-block">
        <h3>Recomendamos los mejores libros</h3>
        <p>
          Nuestras colecciones son una ayuda para elegir las obras adecuadas según
          el estado de ánimo, el tema, la estación del año, la popularidad o el
          criterio de los expertos. Seleccionamos los mejores libros y audiolibros
          en nuestra biblioteca digital para que no tenga que perder tiempo
          buscando. También le informamos sobre los ganadores de premios y
          concursos de libros.
        </p>
      </div>
      <div class="info-block">
        <h3>Estadísticas personales</h3>
        <p>
          Las estadísticas de lectura te motivan a leer más a lo largo de la
          semana, el mes y el año. Cada día registramos el número de páginas
          leídas, dibujamos gráficos en el perfil de la aplicación y enviamos
          estadísticas mensuales a tu correo electrónico. ¿Hace tiempo que no
          retomas el libro? ¡No es el momento de ponerse al día!
        </p>
      </div>
    </div>
  </section>
{% endblock content %}

biblioweb/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Biblioweb: La Biblioteca Virtual al Alcance de un Clic{% endblock title %}

{% block content %}
  <section class="container section hero-section">
    <h1>Biblioweb</h1>
    <p>La biblioteca virtual al alcance de un clic.</p>
    <h2>Top in different genres</h2>
    <p>*Libros ordenados de mayor a menor rating*</p>
    <h2>New best books</h2>
    <p>
      *Mejores libros ordenados de forma descendente según su fecha de ingreso a
      la biblioteca*
    </p>
    {% if books %}
      <ul>
        {% for book in books %}
          <li>
            <a href="{% url 'books:detail' book.slug %}">{{ book.title }}</a>
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <p>There are no books available.</p>
    {% endif %}
    <h2>For children and parents</h2>
    <p>
      *Libros clasificados según géneros aptos para niños y padres. Con mejor
      rating*
    </p>
    <h3>All books are available at the same time</h3>
    <h3>Personal recommendations</h3>
    <h3>Reading statistics</h3>
  </section>
{% endblock content %}